# Generated by Django 3.2.5 on 2022-10-19 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_alter_productinventory_managers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='media',
            name='img_url',
            field=models.ImageField(default='defaults/placeholder.png', help_text='format: required, default-default.png', upload_to='uploads/product_images/', verbose_name='product image'),
        ),
    ]
