# Generated by Django 3.2.5 on 2023-01-25 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('captcha', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='captcha',
            name='web_id',
            field=models.CharField(default='a', max_length=255, unique=True),
            preserve_default=False,
        ),
    ]
