# Generated by Django 4.2 on 2023-06-04 18:22

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="extenduser",
            name="profile_image",
            field=models.ImageField(
                blank=True,
                default="/static/defaults/profile_image.png",
                null=True,
                upload_to="uploads/profile_images/",
            ),
        ),
    ]
