# Generated by Django 4.2 on 2023-06-04 18:22

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("inventory", "0002_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="media",
            name="image",
            field=models.ImageField(
                default="/static/defaults/placeholder.png",
                help_text="format: required, default-default.png",
                upload_to="uploads/product_images/",
                verbose_name="product image",
            ),
        ),
    ]
