# Generated by Django 4.2.4 on 2023-08-16 23:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_alter_media_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='media',
            old_name='product_inventory',
            new_name='inventory',
        ),
        migrations.RenameField(
            model_name='stock',
            old_name='product_inventory',
            new_name='inventory',
        ),
    ]
