# Generated by Django 4.2.4 on 2023-12-28 02:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0004_rename_product_inventory_media_inventory_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='media',
            name='image',
            field=models.ImageField(default='/media/static/defaults/placeholder.png', help_text='format: required, default-default.png', upload_to='uploads/product_images/', verbose_name='product image'),
        ),
    ]
