# Generated by Django 4.2 on 2023-06-04 18:22

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("captcha", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="captcha",
            name="image",
            field=models.ImageField(
                default="/static/defaults/placeholder.png",
                upload_to="uploads/captchas/",
            ),
        ),
    ]
