# Generated by Django 4.2.4 on 2023-12-26 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0002_comment_updated_at_comment_web_id_post_updated_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='thread',
            name='thread_icon',
            field=models.ImageField(blank=True, default='/static/defaults/placeholder.png', null=True, upload_to='uploads/thread_icons/'),
        ),
    ]
