# Generated by Django 4.2.4 on 2023-12-26 17:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0003_thread_thread_icon'),
    ]

    operations = [
        migrations.RenameField(
            model_name='thread',
            old_name='thread_icon',
            new_name='image',
        ),
    ]
