# Generated by Django 4.2.4 on 2023-12-28 02:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0006_thread_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='thread',
            name='image',
            field=models.ImageField(blank=True, default='/media/static/defaults/placeholder.png', null=True, upload_to='uploads/thread_icons/'),
        ),
    ]
