# Generated by Django 3.2.5 on 2022-10-19 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='extenduser',
            name='profile_image',
            field=models.ImageField(blank=True, default='defaults/profile_image.png', null=True, upload_to='uploads/profile_images/'),
        ),
    ]
