# Generated by Django 4.2 on 2023-05-10 12:59

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("payments", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="status",
            field=models.CharField(
                choices=[
                    ("unknown", "unknown"),
                    ("new", "new"),
                    ("paid", "paid"),
                    ("shipped", "shipped"),
                    ("canceled", "canceled"),
                    ("done", "done"),
                    ("objected", "objected"),
                ],
                default="new",
                max_length=255,
            ),
        ),
    ]
