# Generated by Django 3.2.5 on 2022-09-24 16:34

from django.db import migrations, models
import picklefield.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BTCPayClientStore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client', picklefield.fields.PickledObjectField(editable=False)),
            ],
        ),
    ]
