# Generated by Django 3.2.5 on 2023-01-19 10:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0004_auto_20221216_1549'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BTCPayClientStore',
        ),
        migrations.RemoveField(
            model_name='orderinvoice',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='orderinvoice',
            name='expired_at',
        ),
    ]
