# Generated by Django 3.2.5 on 2023-01-24 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0005_auto_20230119_1011'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='email',
            field=models.EmailField(default='test@sloow.de', max_length=254),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='firstname',
            field=models.CharField(default='Greezy', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='lastname',
            field=models.CharField(default='Greed', max_length=100),
            preserve_default=False,
        ),
    ]
