# Generated by Django 4.2.4 on 2023-08-16 23:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('basket', '0002_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='basketobject',
            old_name='product_inventory',
            new_name='inventory',
        ),
    ]
