# Generated by Django 4.2.4 on 2023-08-16 23:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('basket', '0003_rename_product_inventory_basketobject_inventory'),
    ]

    operations = [
        migrations.RenameField(
            model_name='basketobject',
            old_name='quantity',
            new_name='qty',
        ),
    ]
