name: dev
run-name: Dev Server
on: [push]
jobs:
  check-bats-version:
    runs-on: self-hosted
    environment: Dev
    steps:
      - name: Checkout 
        uses: actions/checkout@v3
      - name: Build
        run: docker build -t octoincore ./octoincore
      - name: Run
        run: docker run -it octoincore -p 8000:8000| -e ENV=dev -e ALLOWED_HOSTS -e STORAGE=s3 -e BTCPAY_TOKEN -e BTCPAY_STORE_ID -e POSTGRES_DB -e POSTGRES_USER -e POSTGRES_PASSWORD -e POSTGRES_HOST -e POSTGRES_PORT -e AWS_STORAGE_BUCKET_NAME -e AWS_ACCESS_KEY_ID -e AWS_SECRET_ACCESS_KEY

#       # - name: Secrets
#       #   env:
#       #     ALLOWED_HOSTS: ${{ secrets.ALLOWED_HOSTS }}
#       #     BTCPAY_TOKEN: ${{ secrets.BTCPAY_TOKEN }}
#       #     BTCPAY_STORE_ID: ${{ secrets.BTCPAY_STORE_ID }}
#       #     POSTGRES_DB: ${{ secrets.POSTGRES_DB }}
#       #     POSTGRES_USER: ${{ secrets.POSTGRES_USER }}
#       #     POSTGRES_PASSWORD: ${{ secrets.POSTGRES_PASSWORD }}
#       #     POSTGRES_HOST: ${{ secrets.POSTGRES_HOST }}
#       #     POSTGRES_PORT: ${{ secrets.POSTGRES_PORT }}
#       #     AWS_STORAGE_BUCKET_NAME: ${{ secrets.AWS_STORAGE_BUCKET_NAME }}
#       #     AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
#       #     AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}